version: 2

project_name: kache

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kache
    binary: kache
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - id: kache
    builds:
      - kache
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - image_templates:
      - "ghcr.io/hoangnguyendev3/kache:{{ .Version }}"
      - "ghcr.io/hoangnguyendev3/kache:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

release:
  github:
    owner: hoangNguyenDev3
    name: kache
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
